### PR TITLE
Replace all images to [FontAwesome icons](http://fontawesome.io/)

### PR DESCRIPTION
**Pull request by Kirill**

### CODE REVIEW

**Comment by vboctor** [comment]
Thanks @Kirill for submitting this. @syncguru will be the main reviewer, but I'll add feedback as I try it.

Next to tags you use '-' for deletion rather than 'x' (remove).  We should use the x for collapse and the '-' for collapse.

http://www.screencast.com/t/cI5XdrkGT

**Comment by vboctor** [comment]
Some seems to be wrong with attachments.  In this specific case the attachment file doesn't exist, but I don't think this is the cause.

http://www.screencast.com/t/ILxsF5ZuW

Another example:
http://www.screencast.com/t/L8Qn1HHYKQq

**Comment by vboctor** [comment]
How about replacing the 'Delete' buttons in monitor list with 'x' (remove) icon.
http://www.screencast.com/t/WtpDSVOA4hs

**Comment by vboctor** [comment]
Replace the icon next to the release dates / 'not yet released' in changelog with 'calendar'.
http://www.screencast.com/t/dUb0GE1R8ck

Apply also to Roadmap.

**Comment by Kirill** [comment]
@vboctor, I fix bugs with you find. @syncguru, can you review my patch?

**Comment by syncguru** [comment]
@Kirill - Thanks a lot! This is great.

Few little things remain:
1- Calendar icon need to be switched to FA. See attached. You will need to enable due-date to see it.
screen shot 2016-05-14 at 8 51 19 am

2- Icon sizes in the my-view & view-list pages needs some work. For example, high & critical priority icons are too small. Also in my-view page, icons seems too busy.
3- For tag buttons, what do you think about switching to split buttons. So the delete icon will be part of a larger button instead of stand alone.

Otherwise, this looks good. I will take a stab at these tweak and see if I can suggest few things to you.

**Comment by vboctor** [comment]
I don't like the pen used for edit issue on View Issues page compared to the original image.  I would keep the image for that one.  Any thoughts?

**Comment by Kirill** [comment]
@syncguru I can't change visible tosplit button. Allways have space between buttons.
@vboctor I don't like this idea. May be replace with other [icon](http://fontawesome.io/icons/), for example, fa-pencil-square-o or fa-gog?

**Comment by syncguru** [comment]
@Kirill & @vboctor 
I did some tweaks with the goals to improve the look and feel of the font-awesome icons. I do like to use font-awesome icons only - it is more consistent and give us better performance.

Let me know what you think? I can check my changes to this PR once I hear from you.

screen shot 2016-05-30 at 9 19 30 am
screen shot 2016-05-30 at 9 20 07 am

**Comment by Kirill** [comment]
It's look nice than my version :smile: :+1:

**Comment by vboctor** [comment]
@syncguru @Kirill :+1:

**Comment by Kirill** [comment]
@vboctor 1.4 or 2.0?

**Comment by syncguru** [comment]
Since we are all good. Merging this pull request so I can push my changes on top. 
Thanks @Kirill !!

**Pull request merged**
