### PR TITLE
Improve profile fill-in layout on bug report page

### PR DESCRIPTION
**Pull request by dregad**
- Apply classes to the inner table so it looks more like the main one
- Move 'or_fill_in' text for collapsed section to separate PHP tag so
  it's consistent with open section

### CODE REVIEW

**Comment by dregad** [comment]
Noticed this as I wanted to check whether [#20802](https://www.mantisbt.org/bugs/view.php?id=20802) was fixed in ModernUI (it is).

As a side note, was surprised to see that you're relying on tables for the page layout, since in 1.3 it's mostly done with divs.

**Comment by syncguru** [comment]
@dregad thanks for the PR
As for using tables vs. divs:
If the intention is to create a table, then we should use table tag. Otherwise, we should use divs. Manits is table heavy (data rendered in grids), thus switching to divs to effectively build tables makes things much harder. Table tag is not obsolete in HTML. I kept divs unchanged when we were not drawing tables.

**Comment by dregad** [comment]
Thanks for the feedback. 

I am not an expert in HTML design, but my understanding is that tables (i.e. using tag) are meant to display tabular data, not to structure a page's layout, in which case divs should be used.

I know that Mantis is table-heavy, and the move from table to divs is something that was started in the 1.3 branch before I joined the project. Following this initiative, I continued to convert pages from table-based to div-based layout (using the existing design and CSS).

My surprise came from the fact that in 1.3 branch, _bug_report_page.php_ was changed to use divs in 2014 (see 38f6bb12fb9bb7ec273bd0165c449aa162e04a76) since the table was used for structure, so I expected ModernUI to reflect that change.

This is a bit of a philosophical discussion and somewhat out of this PR's scope but IMO for maintainability it would be good to keep the layout in sync when possible.

**Comment by syncguru** [comment]
👍

**Pull request merged**
